// packages/webplayer-react/src/components/WebPlayer.tsx
import {
  useMemo,
  useEffect,
  type FC as ReactFC,
  type PropsWithChildren as ReactPropsWithChildren,
} from "react";

import type {
  AnalyticsLoadEvent,
  AnalyticsDisplayEvent,
  AnalyticsInteractionEvent,
  AnalyticsErrorEvent,
} from "@car-cutter/analytics";
import {
  DEFAULT_EVENT_PREFIX,
  EVENT_COMPOSITION_LOADING,
  EVENT_COMPOSITION_LOADED,
  EVENT_COMPOSITION_LOAD_ERROR,
  EVENT_ITEM_CHANGE,
  EVENT_EXTEND_MODE_ON,
  EVENT_EXTEND_MODE_OFF,
  EVENT_HOTSPOTS_ON,
  EVENT_HOTSPOTS_OFF,
  EVENT_GALLERY_OPEN,
  EVENT_GALLERY_CLOSE,
  DEFAULT_ANALYTICS_EVENT_PREFIX,
  ANALYTICS_EVENT_LOAD,
  ANALYTICS_EVENT_DISPLAY,
  ANALYTICS_EVENT_INTERACTION,
  ANALYTICS_EVENT_ERROR,
  type MediaItem,
  type Composition,
} from "@car-cutter/core";
import { type WebPlayerProps as WebPlayerCoreProps } from "@car-cutter/core";
import { webPlayerPropsToAttributes } from "@car-cutter/core-wc";

type WebPlayerProps = ReactPropsWithChildren<WebPlayerCoreProps> & {
  onCompositionLoading?: (url: string) => void;
  onCompositionLoaded?: (composition: Composition) => void;
  onCompositionLoadError?: (error: unknown) => void;
  onItemChange?: (props: { index: number; item: MediaItem }) => void;
  onExtendModeOn?: () => void;
  onExtendModeOff?: () => void;
  onHotspotsOn?: () => void;
  onHotspotsOff?: () => void;
  onGalleryOpen?: () => void;
  onGalleryClose?: () => void;
  onAnalyticsLoad?: (event: AnalyticsLoadEvent) => void;
  onAnalyticsDisplay?: (event: AnalyticsDisplayEvent) => void;
  onAnalyticsInteraction?: (event: AnalyticsInteractionEvent) => void;
  onAnalyticsError?: (event: AnalyticsErrorEvent) => void;
} & Pick<React.HTMLAttributes<HTMLElement>, "className" | "style">;

const WebPlayer: ReactFC<WebPlayerProps> = ({
  onCompositionLoading,
  onCompositionLoaded,
  onCompositionLoadError,
  onItemChange,
  onExtendModeOn,
  onExtendModeOff,
  onHotspotsOn,
  onHotspotsOff,
  onGalleryOpen,
  onGalleryClose,
  onAnalyticsLoad,
  onAnalyticsDisplay,
  onAnalyticsInteraction,
  onAnalyticsError,
  className,
  style = {},
  children,
  ...props
}) => {
  const attributes = useMemo(() => {
    const wcAttributes = webPlayerPropsToAttributes(props);

    // Add "class" as r2wc does not support camelCase props
    if (className) {
      Object.assign(wcAttributes, { class: className });
    }

    return wcAttributes;
  }, [className, props]);

  useEffect(() => {
    const eventPrefix = props.eventPrefix ?? DEFAULT_EVENT_PREFIX;
    const analyticsEventPrefix =
      props.analyticsEventPrefix ?? DEFAULT_ANALYTICS_EVENT_PREFIX;

    const generateEventName = (event: string) => `${eventPrefix}${event}`;
    const generateAnalyticsEventName = (event: string) =>
      `${analyticsEventPrefix}${event}`;

    const eventListenerMap = {
      [EVENT_COMPOSITION_LOADING]: onCompositionLoading,
      [EVENT_COMPOSITION_LOADED]: onCompositionLoaded,
      [EVENT_COMPOSITION_LOAD_ERROR]: onCompositionLoadError,
      [EVENT_ITEM_CHANGE]: onItemChange,
      [EVENT_EXTEND_MODE_ON]: onExtendModeOn,
      [EVENT_EXTEND_MODE_OFF]: onExtendModeOff,
      [EVENT_HOTSPOTS_ON]: onHotspotsOn,
      [EVENT_HOTSPOTS_OFF]: onHotspotsOff,
      [EVENT_GALLERY_OPEN]: onGalleryOpen,
      [EVENT_GALLERY_CLOSE]: onGalleryClose,
    };
    const analyticsEventListenerMap = {
      [ANALYTICS_EVENT_LOAD]: onAnalyticsLoad,
      [ANALYTICS_EVENT_DISPLAY]: onAnalyticsDisplay,
      [ANALYTICS_EVENT_INTERACTION]: onAnalyticsInteraction,
      [ANALYTICS_EVENT_ERROR]: onAnalyticsError,
    };

    const eventCbMap = new Map<string, EventListener>();
    const analyticsEventCbMap = new Map<string, EventListener>();

    Object.entries(eventListenerMap).forEach(([event, listener]) => {
      if (!listener) {
        return;
      }

      const eventName = generateEventName(event);
      const eventListener = (event: Event) =>
        listener((event as CustomEvent).detail);

      eventCbMap.set(eventName, eventListener);

      document.addEventListener(eventName, eventListener);
    });

    Object.entries(analyticsEventListenerMap).forEach(([event, listener]) => {
      if (!listener) {
        return;
      }

      const eventName = generateAnalyticsEventName(event);
      const eventListener = (event: Event) =>
        listener((event as CustomEvent).detail);

      analyticsEventCbMap.set(eventName, eventListener);

      document.addEventListener(eventName, eventListener);
    });

    return () => {
      eventCbMap.forEach((eventListener, eventName) => {
        document.removeEventListener(eventName, eventListener);
      });
      analyticsEventCbMap.forEach((eventListener, eventName) => {
        document.removeEventListener(eventName, eventListener);
      });
    };
  }, [
    props.eventPrefix,
    onCompositionLoading,
    onCompositionLoaded,
    onCompositionLoadError,
    onItemChange,
    onExtendModeOn,
    onExtendModeOff,
    onHotspotsOn,
    onHotspotsOff,
    onGalleryOpen,
    onGalleryClose,
    props.analyticsEventPrefix,
    onAnalyticsLoad,
    onAnalyticsDisplay,
    onAnalyticsInteraction,
    onAnalyticsError,
  ]);

  // NOTE: Custom element are "display: inline" by default + Style is there so that React can do its thing
  return (
    <cc-webplayer style={{ display: "block", ...style }} {...attributes}>
      {children}
    </cc-webplayer>
  );
};

export { WebPlayer, type WebPlayerProps };

// packages/webplayer-vue/src/vue2/WebPlayer.vue
<script lang="ts">
import { defineComponent } from "vue";
import {
  DEFAULT_EVENT_PREFIX,
  EVENT_COMPOSITION_LOADING,
  EVENT_COMPOSITION_LOADED,
  EVENT_COMPOSITION_LOAD_ERROR,
  EVENT_ITEM_CHANGE,
  EVENT_EXTEND_MODE_ON,
  EVENT_EXTEND_MODE_OFF,
  EVENT_HOTSPOTS_ON,
  EVENT_HOTSPOTS_OFF,
  EVENT_GALLERY_OPEN,
  EVENT_GALLERY_CLOSE,
  type MediaItem,
  type Composition,
  type WebPlayerProps,
  AnalyticsLoadEvent,
  AnalyticsDisplayEvent,
  AnalyticsInteractionEvent,
  AnalyticsErrorEvent,
  DEFAULT_ANALYTICS_EVENT_PREFIX,
} from "@car-cutter/core";
import {
  ensureCustomElementsDefinition,
  webPlayerPropsToAttributes,
} from "@car-cutter/wc-webplayer";
import {
  ANALYTICS_EVENT_LOAD,
  ANALYTICS_EVENT_DISPLAY,
  ANALYTICS_EVENT_INTERACTION,
  ANALYTICS_EVENT_ERROR,
} from "@car-cutter/core/src/const/webplayer-events";

ensureCustomElementsDefinition();

export type { WebPlayerProps };

export default defineComponent({
  props: {
    compositionUrl: { type: String, required: true },

    hideCategoriesNav: Boolean,
    infiniteCarrousel: Boolean,
    permanentGallery: Boolean,

    mediaLoadStrategy: String,
    minMediaWidth: Number,
    maxMediaWidth: Number,
    preloadRange: Number,
    autoLoad360: Boolean,
    autoLoadInterior360: Boolean,

    categoriesFilter: String,
    extendBehavior: String,
    eventPrefix: String,
    demoSpin: Boolean,
    reverse360: Boolean,
    spinCursor: String,

    analyticsEventPrefix: String,
    analyticsUrl: String,
    analyticsBearer: String,
    analyticsSimpleRequestsOnly: Boolean,
    analyticsDryRun: Boolean,
    analyticsDebug: Boolean,
    monitoring: Boolean,
  },
  data() {
    return {
      eventCbMap: new Map<string, EventListener>(),
      analyticsEventCbMap: new Map<string, EventListener>(),
    };
  },
  computed: {
    attributes() {
      return webPlayerPropsToAttributes(this.$props as WebPlayerProps);
    },
  },
  methods: {
    // Functional events
    generateEventName(event: string): string {
      const eventPrefix = this.eventPrefix || DEFAULT_EVENT_PREFIX;
      return `${eventPrefix}${event}`;
    },
    setupEventListeners(): void {
      const eventListenerMap = {
        [EVENT_COMPOSITION_LOADING]: (url: string) =>
          this.$emit("compositionLoading", url),
        [EVENT_COMPOSITION_LOADED]: (composition: Composition) =>
          this.$emit("compositionLoaded", composition),
        [EVENT_COMPOSITION_LOAD_ERROR]: (error: unknown) =>
          this.$emit("compositionLoadError", error),
        [EVENT_ITEM_CHANGE]: (props: { index: number; item: MediaItem }) =>
          this.$emit("itemChange", props),
        [EVENT_EXTEND_MODE_ON]: () => this.$emit("extendModeOn"),
        [EVENT_EXTEND_MODE_OFF]: () => this.$emit("extendModeOff"),
        [EVENT_HOTSPOTS_ON]: () => this.$emit("hotspotsOn"),
        [EVENT_HOTSPOTS_OFF]: () => this.$emit("hotspotsOff"),
        [EVENT_GALLERY_OPEN]: () => this.$emit("galleryOpen"),
        [EVENT_GALLERY_CLOSE]: () => this.$emit("galleryClose"),
      };

      Object.entries(eventListenerMap).forEach(([event, listener]) => {
        if (!listener) return;

        const eventName = this.generateEventName(event);
        const eventListener = (event: Event) =>
          listener((event as CustomEvent).detail);

        this.eventCbMap.set(eventName, eventListener);
        document.addEventListener(eventName, eventListener);
      });
    },
    // Analytics events
    generateAnalyticsEventName(event: string): string {
      const eventPrefix =
        this.analyticsEventPrefix || DEFAULT_ANALYTICS_EVENT_PREFIX;
      return `${eventPrefix}${event}`;
    },
    setupAnalyticsEventListeners(): void {
      const eventListenerMap = {
        [ANALYTICS_EVENT_LOAD]: (event: AnalyticsLoadEvent) =>
          this.$emit("analyticsLoad", event),
        [ANALYTICS_EVENT_DISPLAY]: (event: AnalyticsDisplayEvent) =>
          this.$emit("analyticsDisplay", event),
        [ANALYTICS_EVENT_INTERACTION]: (event: AnalyticsInteractionEvent) =>
          this.$emit("analyticsInteraction", event),
        [ANALYTICS_EVENT_ERROR]: (event: AnalyticsErrorEvent) =>
          this.$emit("analyticsError", event),
      };
      Object.entries(eventListenerMap).forEach(([event, listener]) => {
        if (!listener) return;

        const eventName = this.generateAnalyticsEventName(event);
        const eventListener = (event: Event) =>
          listener((event as CustomEvent).detail);

        this.analyticsEventCbMap.set(eventName, eventListener);
        document.addEventListener(eventName, eventListener);
      });
    },
  },
  mounted() {
    this.setupEventListeners();
    this.setupAnalyticsEventListeners();
  },
  beforeDestroy() {
    this.eventCbMap.forEach((eventListener, eventName) => {
      document.removeEventListener(eventName, eventListener);
    });
    this.analyticsEventCbMap.forEach((eventListener, eventName) => {
      document.removeEventListener(eventName, eventListener);
    });
  },
});
</script>

<template>
  <cc-webplayer v-bind="attributes">
    <slot></slot>
  </cc-webplayer>
</template>
